# Generated by Django 3.0.3 on 2020-03-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chosenPic',
        ),
        migrations.AlterField(
            model_name='question',
            name='blendedPic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
