# Generated by Django 3.0.3 on 2020-04-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='blendedPic',
        ),
    ]
