# Generated by Django 3.0 on 2019-12-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191220_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='blendedPic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
