# Generated by Django 3.0.3 on 2020-03-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200323_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='ambientBrightness',
            field=models.FloatField(default=0),
        ),
    ]
