# Generated by Django 3.0.3 on 2020-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_blendedpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='flashTempRange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='illuminant',
            field=models.IntegerField(default=0),
        ),
    ]
