# Generated by Django 3.0 on 2019-12-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_blendedpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chosenPic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
