# Generated by Django 3.0.3 on 2020-03-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200324_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='userID',
            field=models.IntegerField(default=0),
        ),
    ]
