# Generated by Django 3.0.3 on 2020-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200520_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='questionID',
            field=models.IntegerField(default=0),
        ),
    ]
