# Generated by Django 3.0.3 on 2020-06-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='flashBrightness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='ambientBrightness',
            field=models.IntegerField(default=0),
        ),
    ]
