# Generated by Django 3.0 on 2019-12-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_finalchoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='edit',
        ),
    ]
