# Generated by Django 3.0.3 on 2020-06-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200603_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='ambientTemp',
        ),
    ]
