# Generated by Django 3.0.3 on 2020-06-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_choice_ambienttemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('ML', 'Male'), ('FE', 'Female'), ('OT', 'Other')], default='ML', max_length=2),
        ),
    ]
