# Generated by Django 3.0.3 on 2020-07-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
