# Generated by Django 3.0.3 on 2020-07-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_question_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='ambient',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='ambientBrightness',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='flash',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='flashBrightness',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='flashTemp',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='flashTempRange',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='illuminant',
        ),
        migrations.RemoveField(
            model_name='question',
            name='set',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='setNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='setNum',
            field=models.IntegerField(default=1),
        ),
    ]
