# Generated by Django 3.0.3 on 2020-07-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_choice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(default='rather not say', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(default='rather not say', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='rather not say', max_length=100),
        ),
    ]
