# Generated by Django 3.0.3 on 2020-07-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200712_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choiceSet',
            field=models.IntegerField(default=0),
        ),
    ]
