# Generated by Django 3.0.3 on 2020-07-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200720_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstTime',
        ),
    ]
