# Generated by Django 3.0.3 on 2020-07-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_question_choiceset'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='flash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='setNum',
            field=models.IntegerField(default=0),
        ),
    ]
