# Generated by Django 3.0.3 on 2020-07-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200717_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='startTime',
            field=models.IntegerField(default=0),
        ),
    ]
