# Generated by Django 3.0.3 on 2020-07-21 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20200720_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='startTime',
        ),
    ]
