# Generated by Django 3.0.3 on 2020-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_remove_question_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='tempNum',
            field=models.IntegerField(default=0),
        ),
    ]
