# Generated by Django 3.0.3 on 2020-07-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_choice_tempnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberOfPics',
            field=models.IntegerField(default=1),
        ),
    ]
