# Generated by Django 3.0.3 on 2020-07-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20200724_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
