# Generated by Django 3.0.3 on 2020-07-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_choice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.CreateModel(
            name='QuestionForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=0)),
                ('choiceSet', models.IntegerField(default=0)),
                ('setNum', models.IntegerField(default=0)),
                ('flashPic', models.ImageField(upload_to='images/')),
                ('ambientPic', models.ImageField(upload_to='images/')),
                ('flash', models.IntegerField(default=0)),
                ('temp', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
    ]
