# Generated by Django 3.0.3 on 2020-07-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20200729_0257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionForUser',
            new_name='Questuser',
        ),
    ]
