# Generated by Django 3.0.3 on 2020-07-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20200729_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='questuser',
            name='ambientPic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='questuser',
            name='flashPic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
