# Generated by Django 3.0.3 on 2020-07-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20200729_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questuser',
            name='ambientPic',
        ),
        migrations.RemoveField(
            model_name='questuser',
            name='flashPic',
        ),
    ]
