# Generated by Django 3.0.3 on 2020-08-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20200729_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='firstSet',
            field=models.BooleanField(default=False),
        ),
    ]
