# Generated by Django 3.0.3 on 2020-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_question_firstset'),
    ]

    operations = [
        migrations.AddField(
            model_name='questuser',
            name='firstSet',
            field=models.BooleanField(default=False),
        ),
    ]
