# Generated by Django 3.0.3 on 2020-08-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_questuser_firstset'),
    ]

    operations = [
        migrations.AddField(
            model_name='questuser',
            name='secondSet',
            field=models.BooleanField(default=False),
        ),
    ]
